on: [push]
env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
  NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        id: build
        run: echo "build_output=$(nix-build)" >> $GITHUB_OUTPUT
      
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_KEY }}
          cleanup: false
          neocities_supporter: true
          preview_before_deploy: false
          dist_dir: ${{ steps.build.outputs.build_output }}
