on: [push]
env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
jobs:
  ls:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls ${{ github.workspace }}
          nix-build