on: [push]
jobs:
  ls:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: repository: 'https://git.chobble.com/hosted-by-chobble/marky-t/'
      - run: |
          ls ${{ github.workspace }}    